### ISSUE TITLE
再投稿 チューナーオープン失敗時の仕様について

### ISSUE THREAD

**Issue by sumire608** [xtne6f/EDCB#23]
ISSUE版が有効になったので再投稿です。
10.69人柱版ではチューナーオープン失敗時に自動的に予約を予備のチューナーに順番から割り当てられましたが、今のxtne6f版ではできません。そのままエラーメッセージが出て終わる仕様です。
どうかこの機能を対応あるいは復帰させて頂けないでしょうか。

**Comment by xtne6f** [comment]
その機能、復活させるかどうか迷います。
チューナーオープン失敗というのは、当該チューナーが他ソフトで使用中の場合だと思いますが、TVTestではEpgTimerPlugIn(またはEdcbPlugIn)を使用していれば事前に終了させるので、その機能は不要です。その他のソフトでも、視聴などを低順位のチューナーから使っていればやはり不要です（このへんReadmeが不足してる気がする）。EpgTimer経由の視聴機能も基本的に低順位から使われます。
利用者がチューナーを不適切に運用した場合にそなえる保険のような機能なら、使用予定チューナーの混乱やソースコードの複雑さが増すだけなので、あまり復活させたくはないです。

…と、文句ばかりですみませんが、たとえばProxy系のBonDriverなどで自分の予想していない長所があるかもしれないと思い、その点で迷っています。この再割り当ての機能なにか有用な場面があるでしょうか。

**Comment by sumire608** [comment]
たとえばシェアハウスで2人以上が使う場合や、メイン録画サーバーがトラブルでダウンした時など。
そんな時はやっぱり自動的にS1や予備サーバーに切り替えてほしいわね。

**Comment by xtne6f** [comment]
それらはチューナーオープン失敗として観測できる（この機能と関係のある）ケースなのでしょうか？

**Comment by xtne6f** [comment]
なるほど、Proxy系BonDriverをネットワーク経由で使用する場合ということですか

**Comment by sumire608** [comment]
そうそうそれ。
そこらへんのコードは人柱版に含まれているので移植しようにも手間がそんなにかからないと思いますが

**Comment by xtne6f** [comment]
デフォルトで無効の「チューナーの起動に失敗したとき、ほかのチューナーで再試行する」オプションとして復活させました( b8188c96555506e70e8fa89a1861b0abc2ef3096 )。
予定外のチューナーが使われることや、この機能もともと原作のReadmeにも説明がない？ように思うので、デフォルトで無効としたほうが混乱がないと考えました。

**Comment by sumire608** [comment]
オプションをオンにしてテストしてみたら機能が正常に作動していました。
ご対応ありがとうございました

**Comment by xtne6f** [comment]
テストありがとうございます。マージ完了したため閉じます

**Comment by D0koka** [comment]
PT3、2枚ざしでWin10 21H2環境です。EDCBでは大変お世話になりありがとうございます。使用しているEDCBは、つくみ島で配布されている EDCB-210828.zip です。同時にTvtestも TVTest-0.10.0-210812.zip をつかわさせていただいています。BondriverはBonDriver_PTx-ST_mod-masterを自ビルドして使わせていただいています。時々EDCBがチューナー不足で自動録画ができなくなります。原因はEDCBで自動予約してBondriverが使われるのを知らずに、先行してTvtestで同じBondriverを使っていると、EDCBのチューナー自動回避にチェックを入れているにもかかわらず、回避されずにチューナー不足が発生してしまうことでした。　このコーナーでは他のチューナーで再試行と書かれていますが、当方ではうまく動作していません。どこを直せばよいかご指導いただきたく、よろしくお願いいたします。

**Comment by xtne6f** [comment]
BonDriver_PTx-ST_modの設定などをどうしているのかわからないのでなんとも言えないですが、「チューナーの起動に失敗したとき、ほかのチューナーで再試行する」を有効にしていてチューナーの起動に失敗したとき

`●予約(ID={予約ID})にNGチューナー(ID={チューナーID})を追加します`

というログがデバッグ出力 (EpgTimerSrv設定→その他→デバッグ出力をファイルに保存する) されるはずなので、まずこれが出力されているか教えてください。
EpgTimerSrv設定→基本設定のBonDriverのチューナー数がBonDriver_PTx-ST_modの設定と矛盾していないかも確認してください。

**Comment by D0koka** [comment]
xtne6f/EDCB　様

早速のご連絡ありがとうございます。お世話になります。


＞EpgTimerSrv設定→基本設定のBonDriverのチューナー数がBonDriver_PTx-ST_modの設定と矛盾していないかも確認してください
この設定で1カ月ほど悩みましたが、現状のBonDriver　Holderの中は、
BonDriver_PTx-S.ChSet.txt
BonDriver_PTx-S.dll
BonDriver_PTx-ST.ini
BonDriver_PTx-T.ChSet.txt
BonDriver_PTx-T.dll
PTxCtrl.exe
PTxScanS.exe
Readme.MD
Readme.txt
Setting　Holderの中は
BonDriver_PTx-S(PTx ISDB-S).ChSet4.txt
BonDriver_PTx-T(PTx ISDB-T).ChSet4.txt
ChSet5.txt
EpgAutoAdd.txtRecInfo.txt
RecInfo2.txt
RecInfo2Data.bin
Reserve.txt
です。
チューナー数などは、EpgTimerSrv.iniに反映されていると思いますので、添付させていただきます。
現在、デバッグ出力をログに残すを設定していませんので、早速設定して確認します。
（現在、EpgDataCap_Bon（人柱版１０．６６）で録画運用中のため、録画終了後に確認します。）

早急なご連絡痛み入ります。ありがとうございました。

**Comment by D0koka** [comment]
xtne6f/EDCB 様

お世話になります。
早速、ログを取る設定にして予約してみましたが、今日はチューナーオープンの失敗が出ず、ログが取れませんでした。すみません。
ただ、添付の絵のように、チューナー画面で、同一のチューナーで二つの番組を録画するような設定（ID00000002）が出ました。
録画は正常に行われていましたが、原因は不明です。

今後、ログが取れましたら、再度ご連絡させていただきます。
ありがとうございました。

追伸：xtne6f/EDCB様のEDCBは予約一覧からの右クリックで、大変沢山のことができ、同一番組のチェック、番組表へのジャンプなど、とても助かる項目が多く、大変重宝させていただいています。　ありがとうございます。
寒くなるようです、お体大切にお過ごしくださいますように。

失礼いたします。

**Comment by xtne6f** [comment]
ありがとうございます。
添付ファイルはGitHubの転送メールからの返信ですと削除されてしまうようなので
https://github.com/xtne6f/EDCB/issues/23 のほうに直接書き込んだほうが良いと思われます。
`EpgTimerSrv.ini` をメモ帳などで開くと、たとえば
```
[BonDriver_Hogehoge.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=0
```
のようにBonDriverごとのセクションがあるので、この部分だけコピペして頂ければおそらく十分です。

ご丁寧なメール恐縮です。お互い暖かくして過ごしましょう。

**Comment by D0koka** [comment]
早速のご連絡、ありがとうございます。ご指示いただいた部分のコピーを張ります。
[BonDriver_PT3-S0.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=6
[BonDriver_PT3-S1.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=4
[BonDriver_PT3-S2.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=2
[BonDriver_PT3-S3.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=0
[BonDriver_PT3-T0.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=7
[BonDriver_PT3-T1.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=5
[BonDriver_PT3-T2.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=3
[BonDriver_PT3-T3.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=1
[BonDriver_PTx-S.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=0
[BonDriver_PTx-T.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=1

BonDriver_PT3-S0~T3.dllの記述は、BonDriver_PTx運用以前のものがそのまま残ってしまったようです。現在はBonDriver Holderの中には残っていません。

よろしくお願いいたします。

**Comment by xtne6f** [comment]
> ただ、添付の絵のように、チューナー画面で、同一のチューナーで二つの番組を録画するような設定（ID00000002）が出ました。

もしもその番組のOriginalNetworkIDとTransportStreamIDが同じならその動作は正常です。そうでないないなら、可能なら画像をここに貼り付けるか詳細に説明してもらえればと思います。
PT3の2枚刺し環境だと思います (前コメントで説明済みでしたね…) が
> 早速、ログを取る設定にして予約してみましたが、今日はチューナーオープンの失敗が出ず、ログが取れませんでした。

とのことで確実に再現する問題ではないのですね。しばらく様子見が必要かもしれません。
ログについてはEpgDataCap_Bon.exeにも同様に保存する設定があるので、こちらもしばらく有効にしておくとよいかもしれません。

**Comment by D0koka** [comment]
xtne6f/EDCB 様

お世話になります。
実は#23にご指示のEpgTimerSrv.ini場所のコピーを上げたのですが、反映されていないようなので、
再度こちらに書かせていただきます。
[TVTEST]
Num=7
0=BonDriver_PT3-S0.dll
1=BonDriver_PT3-S1.dll
2=BonDriver_PT3-S2.dll
3=BonDriver_PT3-S3.dll
4=BonDriver_PT3-T0.dll
5=BonDriver_PT3-T1.dll
6=BonDriver_PT3-T2.dll
[BonDriver_PT3-S0.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=6
[BonDriver_PT3-S1.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=4
[BonDriver_PT3-S2.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=2
[BonDriver_PT3-S3.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=0
[BonDriver_PT3-T0.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=7
[BonDriver_PT3-T1.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=5
[BonDriver_PT3-T2.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=3
[BonDriver_PT3-T3.dll]
Count=1
GetEpg=1
EPGCount=0
Priority=1
[BonDriver_PTx-S.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=0
[BonDriver_PTx-T.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=1
[REC_DEF]

以上です
。[BonDriver_PT3-S0∼T3.dll]は[BonDriver_PTx-ST.dll]導入以前に使用していたもので、それが消えずに残っていたものと思います。現在、BonDriver Holder にはBonDriver_PT3-S0∼T3.dllは残っていません。

ご厄介をおかけしますが、よろしくお願いいたします。

**Comment by D0koka** [comment]
xtne6f/EDCB 様

お世話になります。

先のチューナー部の件、わかりました。
EDCBの設定、外部アプリケーションの設定でTVTestを指定し、市長に使用するBonDriver として、以前のものが残ったままで、PTx-ST.dllの指定をしていませんでした。これを現在使用中のBonDriver に変更したところ、
[TVTEST]
Num=2
0=BonDriver_PTx-S.dll
1=BonDriver_PTx-T.dll

[BonDriver_PTx-S.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=0
[BonDriver_PTx-T.dll]
Count=4
GetEpg=1
EPGCount=0
Priority=1
[REC_DEF]

に変更されていました。お騒がせしてすみませんでした。

最後に、予約一覧の一番左のところに、2欄あって、左側にいろいろな色が付くのが不思議だったのですが、これはその番組のジャンルを表しているのだと気が付きました。　多分Readmeに載ってなかった仕様だと思いますが、とても有用でありがたいです。

今後とも、xtne6f/EDCB活用させて頂きます。
ありがとうございました。
