### ISSUE TITLE
リモート視聴の優先度をEPG取得より高く

### ISSUE THREAD

**Issue by corfton** [xtne6f/EDCB#26]
EPG取得に使用するチューナー数を"すべて"にすると、EPG取得中はEMWUI Material WebUIでのリモート視聴ができません。
優先度的に、録画 > リモート視聴 > EPG取得 のような形で使えればいいなと思うのですが、いかがでしょうか。

**Comment by xtne6f** [comment]
視聴中にEPG取得がはじまるときは視聴チューナーのEPG取得がキャンセルされる（リモート視聴>EPG取得）ので、それとの対称性を考えてもより良いと思います。
仕様変更なのでいくらか説明は要りますが、提案通りに変更します。

**Comment by corfton** [comment]
ビルドして期待通りの動作を確認しました。素早いご対応をどうもありがとうございました!!
