### ISSUE TITLE
EdcbPluginが利用するBonDriverで排他要求がだせるように

### ISSUE THREAD

**Issue by 5ym** [xtne6f/EDCB#28]
現状EdcbPluginでの録画時にチャンネルスキャンで使用したBonDriverとなっているが録画で排他要求を出したいときは別途視聴用BonDriverを用意する必要があるように思うのですが仕様でしょうか

**Comment by xtne6f** [comment]
BonDriver共有ソフトを使用した場合に、チャンネル争いに強いBonDriverと弱いBonDriverを用意する必要があるか、ということでしょうか？
必要かどうかは共有ソフトの設定次第かもしれませんが、EDCBでは共有ソフト内部の排他要求は制御できない（関知しない）ので、仕様ということになると思います。

**Comment by 5ym** [comment]
迅速なご対応ありがとうございます。仕様ということですが現状このように https://github.com/16dyui/PT3-soft/tree/master/TVTest/view 排他要求をしないiniのBonDriverを用意して視聴しているのですがTvtestの仕様でチューナー選択が原則直下のディレクトリとなっているため不便な状況です。EdcbPluginから使用する使用するBonDriverのディレクトリまたはiniだけを変更することはできないでしょうか。

**Comment by xtne6f** [comment]
iniはそれに対応するBonDriverが内部で読み込むので、EDCB側で変更することはできません。TVTest自体はディレクトリ配下にもBonDriverを置けたような気がします（？）が、少なくともEDCBでは難しい（EDCBの設定項目など含めて大工事になる）です。
ただ、`BonDriver_*.dll`の`*`の部分は任意ではないのでしょうか。ディレクトリを作りたい理由はなんですか？

**Comment by 5ym** [comment]
すみませんBonDriver側の仕様を失念しておりました。BonDriverファイル名の変更でなんとかなりそうです。お手数おかけしましたありがとうございます。
