### ISSUE TITLE
録画終了時にDropがカウントされることがある

### ISSUE THREAD

**Issue by SeishiHRGSH** [xtne6f/EDCB#30]
Dropが少し発生しているので詳細を確認したら、
ちょうど録画終了あたりで発生したような発生時刻が記録されていました。
録画停止の内部処理の順に工夫が必要なのかも。

Drop:1でも録画済み一覧で赤く強調表示されるので目立ってしまいますが、
録画ターゲットは全く無傷なので、あまり気にはしていません。

**Comment by xtne6f** [comment]
それは特定番組の特定ストリーム（字幕など）の番組終了点で発生していないでしょうか
だとすれば恐らく放送自体にDropが含まれます
（思い当たる節があるので…）

**Comment by SeishiHRGSH** [comment]
そう言われてみれば、このチャンネルでは字幕が、
あのチャンネルではECMがということは、有るような気がします。
一度PCの時計が狂ったことがあって、それ以来、
録画マージンを大き目に（といっても５秒でしたが）したのが裏目に出たのかも。

**Comment by xtne6f** [comment]
受信側でできることはなさそうに思うので、とりあえず閉じます。
