### ISSUE TITLE
edcb録画中の時だけwindowsが再起動されます。

### ISSUE THREAD

**Issue by sasori0623** [xtne6f/EDCB#47]
ここ1週間、勝手に録画中再起動されてしまいます。

イベントビュアーを見ると、wininit.exe Localhost(120.0.0.1)　が勝手に再起動し、
0x80070000と言うコードが出ております。

治したいのですが解決策は有りますでしょうか？

よろしくお願いします。

環境

windows10
spinelを使用
edcbは最新バージョンを使用しております。

pt2 4枚
w3pe 1枚
pt3二枚

全てspinelでまとめております。

**Comment by SeishiHRGSH** [comment]
勝手に再起動という場合、原因をEDBCに求めるべきではないと思いますが....

**Comment by xtne6f** [comment]
自分もまずWindowsUpdateの線を疑います。アプリケーションから普通に `ExitWindowsEx(EWX_REBOOT)` などのWin32APIを呼んで再起動する限り、おそらく`0x80070000`は出ないので。
Updateによる再起動を避けるノウハウは色々蓄積されているように思うので、自身で検索して対応してもらえればと思います。
それでも解決しない場合やEDCBの録画中だけ再起動されてしまうようなときは、EpgTimerSrvやEpgDataCap_Bonの「デバッグ出力をファイルに保存する」を有効にしてログを出力してみてください。
今ある情報だけでは何が起こっているかちょっとわかりません。

**Comment by sasori0623** [comment]
御返信有難う御座います。
WindowsUpdateサービスは再起動の発生する前からOFFにしており、WindowsUpdateでは無いと思うのですが。。

また、OSを初期化。（HDDをフォーマットしクリーンインストール）をしましたが、同様の症状が出ております。

ちなみにWindows11に致しました。

また、EDCBの方のログを取ってみた所、再起動とは関係無いのですが、C:\PT2\EDCB\x64\B25Decoder.dll のロードに失敗しました。と言うEDCBのログが出ていることに気づきました。

また、EPGTIMERの方は、「[211110145756.339] err default cmd 18」等、数値が羅列されているエラーが出ていることに気が付きました。

多分関係無いと思うんですが、ローカルホストが再起動コマンドを送っていることになっていた為、EDCBの方のネットワーク設定でローカルホストを指定していたところを無くしてみました。

これで治らなかったら本当に原因が分らなくなります。

**Comment by xtne6f** [comment]
> EDCBの方のネットワーク設定でローカルホストを指定していたところ

これちょっとよく分からないですがどこの設定でしょうか

EpgTimerSrv設定のその他にある「ネットワーク接続を許可する (EpgTimerNW用)」は未チェック(無効)状態ですか？
ふつう未チェックのはずですがもしチェック状態なら、そのポート4510が決して外部(ルーターの外側)からアクセスできないことを確かめてください。

`err default cmd 18` の数字(18の部分)はランダムでしょうか？ほかにどんな数値が羅列されていますか？
正常ならここに18など来るはずないので、EDCBがちゃんと動いてないか設定がおかしい可能性がでてきました。

EDCBは最新バージョンとのことなので `work-plus-s-210828` あたりだと思いますが、VisualStudioのバージョンなどビルド環境を教えてください。

**Comment by xtne6f** [comment]
…もしかしたらですけど、EpgDataCap_Bonのネットワーク設定のTCP送信先に
`127.0.0.1` かつ ポート `4510` を追加してないでしょうか？
もしそうならEpgDataCap_BonのTCP送信先はEpgTimerSrv設定のネットワーク接続とはまったく無関係なので、送信先から削除してください。

**Comment by sasori0623** [comment]
[EpgTimerSrvDebugLog.txt](https://github.com/xtne6f/EDCB/files/7518882/EpgTimerSrvDebugLog.txt)
[EpgDataCap_Bon_DebugLog-0.txt](https://github.com/xtne6f/EDCB/files/7518884/EpgDataCap_Bon_DebugLog-0.txt)

御世話になっております。お返事誠に有難う御座います。

こちらがLOGファイルです。

VisualStudioのヴァージョンは、
VisualStudio　2019
　
製品ヴァージョン
16.11.31727386
です。

＞もしかしたらですけど、EpgDataCap_Bonのネットワーク設定のTCP送信先に
127.0.0.1 かつ ポート 4510 を追加してないでしょうか？

追加していたのを昨日気が付き、削除致しました。また、BonDriverを別のにし、只今録画をしておりますが、4番組同時録画で実験したところ、今現在再起動は起きてません。

Errorのログの詳細が分らない為、対応が出来ない状態ですので、ご教授願えれば幸いです。

宜しくお願いいたします。

**Comment by xtne6f** [comment]
返答ありがとうございます。ログから考えてほぼ間違いなくそのネットワーク設定が原因と思います。

ポート 4510 は予約の確認や制御のためにあるものなので、そこに想定外のデータをEpgDataCap_Bonが送り込んだために、予約開始後に「PCの再起動」という制御が発動したのだと思います。

EpgTimerSrv設定のその他にある「ネットワーク接続を許可する (EpgTimerNW用)」は基本的に EpgTimerNW という、ほかのPCから予約を確認したりするソフトのためにあるもので、使っていないなら未チェック(無効)状態でかまいません。

EpgDataCap_Bonのネットワーク設定も基本的にTVTestでのリモート視聴などのためにあるので、使っていないなら空欄でかまいません。

**Comment by sasori0623** [comment]
ご返答感謝いたします。リモート視聴をしていた為、リモート視聴で中々上手く行かず、やっと見れるようになり、その設定のままで居た次第です。

今の現状でネットワーク視聴と、外部予約等は完結しておりますので、ネットワーク設定を変えた状態で使ってみようと思っております。

大変ご迷惑をおかけ致し　申し訳ございませんでした。

今後も使わさせて頂きます。

何卒宜しくお願いいたします。

**Comment by xtne6f** [comment]
こちらは解決と思われるので閉じます。
