### ISSUE TITLE
EDCBで何度チャンネルスキャンをしてもスターチャンネル3を視聴しようとするとスターチャンネル２が再生される

### ISSUE THREAD

**Issue by sasori0623** [xtne6f/EDCB#48]
御世話になります。以前御回答頂き誠に有難う御座いました。
再度質問誠に申し訳ございませんが、何度検索をし、設定をしようとしても合っているのにも関わらず、題名通り、スターチャンネル３を視聴しようとするとスターチャンネル２が再生されてしまう問題が発生いたし悪戦苦闘しております。

PT3のBonDriver_PT3-S.ChSet　、　PT2のBonDriver_PT-S.ChSet　も書き換え、Settingの中のチャンネルデータ、EPG全部削除しスキャンしても変わらない状況で、TVTESTの方でスターチャンネル３を見ようとすると視聴出来ているので、EDCBの問題かと思い投稿させて頂きました。

ちなみに、BonDriver_Spinel_PT3-S0(Spinel：PT3_0／S0).ChSet4　の中のデータ、ChSet5の中のデータをテキストで見ましたが、チャンネル設定等は特に問題無く、合っている状態です。

間違えていれば分かるのですが、合っているので分らない状況で御座います。

ChSetのデータ等添付致しますので、御教授宜しくお願いいたします。

[BonDriver_PT3-S(PT3 ISDB-S).ChSet4.txt](https://github.com/xtne6f/EDCB/files/7586007/BonDriver_PT3-S.PT3.ISDB-S.ChSet4.txt)
[BonDriver_PT3-S.ChSet.txt](https://github.com/xtne6f/EDCB/files/7586008/BonDriver_PT3-S.ChSet.txt)
[ChSet5.txt](https://github.com/xtne6f/EDCB/files/7586009/ChSet5.txt)

**Comment by sasori0623** [comment]
Chsetを削除し、更新し、古いチャンネルを消したのですが、同様の症状が治らない感じです。

チャンネルスキャンをし更新されたものを新たに添付致します。

宜しくお願いいたします。

[ChSet5.txt](https://github.com/xtne6f/EDCB/files/7588089/ChSet5.txt)
[BonDriver_Spinel_PT3-S0(Spinel：PT3_0／S0).ChSet4.txt](https://github.com/xtne6f/EDCB/files/7588090/BonDriver_Spinel_PT3-S0.Spinel.PT3_0.S0.ChSet4.txt)

**Comment by xtne6f** [comment]
更新前のチャンネルデータだと厄介なことになりそうな感じはしますが
更新後にEpgTimerSrvの再起動は行ったでしょうか？
あと「視聴」と書いてますが EDCB の視聴予約でしょうか？

**Comment by sasori0623** [comment]
御回答誠に有難う御座います。
＞更新前のチャンネルデータだと厄介なことになりそうな感じはしますが
更新後にEpgTimerSrvの再起動は行ったでしょうか？

PCの再起動、EpgTimerSrvの再起動、両方行いました。

＞あと「視聴」と書いてますが EDCB の視聴予約でしょうか？

EDCBの視聴予約では、ランダムで、スターチャンネル２になってしまう事と、スターチャンネル３が録画される事。両方とも有ります。

また、EMWUIのリモート視聴では、スターチャンネル3が再生されます。

ですが、EDCBのTCP視聴。（TVTESTのBondriver　TCPでの視聴）KonomiTVでの視聴ですと、スターチャンネル２になってしまいます。

Settingフォルダーの中のEPG、チャンネルデータを消し、チャンネルスキャンをし、再起動しても改善されません。

宜しくお願いいたします。

**Comment by xtne6f** [comment]
スターチャンネルだけならかなり謎ですが、もしその他のチャンネルでもそうなるなら
EpgDataCap_Bonの動作設定の「全サービスを処理対象とする」にチェックが入ってないか確認してください

**Comment by sasori0623** [comment]
御連絡誠に有難う御座います。

全サービスを処理対象とする。　のチェックを外した所　改善されました。有難う御座いました。

毎度御教授頂きまして御手数をお掛け致しました。有難う御座いました。

今後とも使わさせて頂きます。　
何卒宜しくお願いいたします。
