### ISSUE TITLE
  <SearchKeyServiceList>が保存されません

### ISSUE THREAD

**Issue by pikesaury** [xtne6f/EDCB#49]
xtne6fさんいつも素敵なソフトをありがとうございます。
いつから発生しているかはっきりしないのですが、EpgTimer.exe.xml or EpgTimerNW.exe.xml において、  SearchKeyServiceListが保存されなくなっているようです。
検索条件でチャンネルを外すorつけるしても、次に開くと前の状態に戻っています。
念のためビルドのし直しや、 xtne6fさんがビルドした物を使ってみましたが現象は改善されませんでした。当方Windows10Pro 20H2 64bit環境となります。
もしお心当たりの事があればご教示いただけますと幸いです。

**Comment by xtne6f** [comment]
ありがとうございます。こちらの環境では問題なく保存される感じです (Windows10Pro 21H1 64bit)。

たぶんこの設定だと思うのですが、画像の①だけでなく②のOKボタンを押すまで変更内容が確定しないという微妙に分かりづらい仕様でして、いちど確認してもらえればと思います。
![search](https://user-images.githubusercontent.com/2673799/145702449-cb1924ac-aba1-43bb-be77-1d2e21dc3a5b.jpg)

**Comment by pikesaury** [comment]
xtne6fさん早速のご教示ありがとうございます！
根本的な操作をどこかで勘違いしていたようでした。
丁寧に教えてくださりありがとうございます！
Closeさせていただきます。

**Comment by xtne6f** [comment]
了解です。検索条件のところの設定ダイアログ、やはりわかりづらいですね…。何か注釈など入れようと思います。
