### ISSUE TITLE
番組名で再検索を実行した時の挙動について

### ISSUE THREAD

**Issue by pikesaury** [xtne6f/EDCB#61]
お世話になります。EDCB便利に利用させて頂いております。ありがとうございます。

以下につきご相談があり投稿いたしました。

１）検索→検索キーワードに番組名の一部を入れて検索
２）複数表示される候補から該当番組を右クリックし番組名で再検索

を実施した時の挙動についてです。

まずChSet5.txtからですが、以下のようになっています。
※今回の該当箇所のみです

日テレ１	日本テレビ	32738	32738	1040	1	0	1	1
日テレ２	日本テレビ	32738	32738	1041	1	0	1	1
日テレ臨時	日本テレビ	32738	32738	1044	161	0	0	0
日本テレビ	日本テレビ	32738	32738	1424	192	1	0	0
ＴＢＳ１	ＴＢＳ	32739	32739	1048	1	0	1	1
ＴＢＳ２	ＴＢＳ	32739	32739	1049	1	0	1	1
Ｇガイド	ＴＢＳ	32739	32739	1183	192	0	0	0
ＴＢＳ	ＴＢＳ	32739	32739	1432	192	1	0	0
フジテレビ	フジテレビジョン	32740	32740	1056	1	0	1	1
フジテレビ	フジテレビジョン	32740	32740	1057	1	0	1	1
フジテレビ	フジテレビジョン	32740	32740	1058	1	0	1	1
フジテレビ臨時	フジテレビジョン	32740	32740	1060	161	0	0	0
フジテレビ	フジテレビジョン	32740	32740	1440	192	1	0	0
テレビ朝日	テレビ朝日	32741	32741	1064	1	0	1	1
テレビ朝日	テレビ朝日	32741	32741	1065	1	0	1	1
テレビ朝日	テレビ朝日	32741	32741	1066	1	0	1	1
テレビ朝日	テレビ朝日	32741	32741	1448	192	1	0	0
テレビ東京１	テレビ東京	32742	32742	1072	1	0	1	1
テレビ東京２	テレビ東京	32742	32742	1073	1	0	1	1
テレビ東京３	テレビ東京	32742	32742	1074	1	0	1	1
臨時サービス	テレビ東京	32742	32742	1078	161	0	0	0
テレビ東京携帯	テレビ東京	32742	32742	1456	192	1	0	0

続いて、検索に表示される局名は順番は以下になっています。
映像のみにチェックをしているのでフルセグのみチェックが入っています。

日テレ１　フルセグ
日テレ２　フルセグ
日テレ臨時　
ＴＢＳ１　フルセグ
ＴＢＳ２　フルセグ
Ｇガイド
フジテレビ　フルセグ
フジテレビ　フルセグ
フジテレビ　フルセグ
フジテレビ臨時
テレビ朝日　フルセグ
テレビ朝日　フルセグ
テレビ朝日　フルセグ
テレビ東京１　フルセグ　
テレビ東京２　フルセグ
テレビ東京３　フルセグ
～中略～
日本テレビ　ワンセグ
ＴＢＳ　ワンセグ
フジテレビ　ワンセグ
テレビ朝日　ワンセグ
～以下略～

と並んでいます。

当方の地域（関東）では、見ての通りなのですが、
フジテレビ、テレビ朝日の2局がワンセグとフルセグで同じ局名になっています。

この状態で冒頭の１）→２）を行うと、「映像のみ」にチェックをして状態でも、
ワンセグ放送にもチェックが入ってしまいます。

これを見落としてしまう場合があり、
録画時にフルセグとワンセグの両方が録画されてしまいます。

ChSet5.txtをいじり、

フジテレビ携帯、テレビ朝日携帯

などと改名すれば解決する事は確認しているのですが、
当方はMLT5PEという地デジ、衛星の自動切り替えチューナーをつかっており、
BSのトラポン移動で再編成があった際、チャンネル再設定をし直すと、
地デジの局名も巻き戻ってしまう環境という状況です。

そこで、２）の再検索を行う際に、
映像のみにチェックが入っている場合、＆条件としていただき、
ワンセグのチェックが対象外になるような変更は検討可能でしょうか。

ちょっとした使い勝手の改善ですが、ご検討頂けますと幸いです。
どうぞよろしくお願いします。

**Comment by xtne6f** [comment]
ありがとうございます。たしかに変な挙動をしますね。
局名という一意でないもので再検索するのが問題だと思うので fc26e0f20e6bafc07f9c6b1c6b6f8b5e54056639 のように修正します。これで期待する動作になると思います。（フォーク以前からの実装なのでどうしてこのような挙動にしたのかは不明）

**Comment by pikesaury** [comment]
対応ありがとうございます。
work-plus-sにマージされましたら確認させて頂きます！

**Comment by pikesaury** [comment]
work-plus-sにマージ頂きましたので確認させて頂きました。
まず当方環境ではフジテレビ、テレ朝の両局において、

１）検索→検索キーワードに番組名の一部を入れて検索
２）複数表示される候補から該当番組を右クリックし番組名で再検索

で、ワンセグ局が選択される事は無くなりました。ありがとうございます。

一方で、これまでは地デジ全局（メイン＋サブ＋サブ）の３chすべてが予約対象となっていましたが、地デジのメインchのみがチェックされ、サブchの2局はチェックされないようになりました。

今回の変更ではサービスID単位で検索をするようになったので、この挙動はこうなるだろうと理解している事と、今のところメインとサブで毎週番組が入れ替わるような番組表は存在しないので録画失敗などには繋がらないと思いますが、恐らく元作者の意図としては、このような事を防ぐために、地デジ３局すべてにチェックが入る仕様だったんだろうなと感じました。

ただ、今回の変更で概ね当方の要望は満たせると思いますので、こちらはcloseさせていただきます。
また使い勝手で相談があれば、別Issueをたてさせて頂きます。

ありがとうございました！
