### ISSUE TITLE
EdcbPlugIn使用時にCS110度などのチャンネルでドロップログ(.err)のScramble値が増加する

### ISSUE THREAD

**Issue by laind1st** [xtne6f/EDCB#66]
EdcbPlugIn使用時ですがCS110度やスカパー！プレミアムなど1チャンネルに複数のサービス(放送局？)が存在する場合に
ドロップログ(.err)に録画対象でないサービスのログも記録されてしまいScramble値が増加した状態でログが記録されます。
"#$SID16$#"を設定して指定サービス相当で録画をしており録画ファイルその物は問題ありませんが
上記ドロップログの問題を回避する方法は何かありますか。

**Comment by xtne6f** [comment]
指定サービスのフィルタリングをドロップログにも正しく反映するよう改善します（次のリリースで 128ca5028781d897de4ca5997a741bb87731fb1e を適用）。
個人的にScramble値をとくに気にしない癖がついていてドロップログまわりは若干手抜きしていました。

ドロップログ用にTSパケットを解析するロジック（=ストリームコールバック）とファイルを保存するロジック（=Write_OneService.dll）の場所がことなっているため、実際に保存されるファイルの内容と厳密には一致しないのですが、おおむね正しくなるはずです。（例えばTVTestの設定の「データ放送を保存する」をオフにしてもドロップログ上ではデータ放送のパケットもカウントされてしまう）

**Comment by laind1st** [comment]
改善ありがとうございます。
