### ISSUE TITLE
要望：番組名で再検索の挙動につきまして

### ISSUE THREAD

**Issue by pikesaury** [xtne6f/EDCB#67]
検索画面→検索キーワード入力→検索ボタン→検索結果から番組名を右クリック→番組名で再検索の操作時、
現状ですとNOTキーワードやジャンル絞り込みなどもクリアされてしまいます。

しかしながら、この機能の用途として「検索キーワード」と「サービス絞り込み」の2点のみが更新され、
それ以外の条件は一切変更されないほうが使い勝手が良いと思われます。

こちら番組名で再検索の挙動変更を検討頂けないでしょうか。
よろしくお願いします。

**Comment by xtne6f** [comment]
提案たしかにその通りに思うので挙動変更します。( commit: https://github.com/xtne6f/EDCB/commit/de8e3c87ef975b87228e53109bc902547d4e1ef8 )

**Comment by pikesaury** [comment]
開発決定ありがとうございます！
