### ISSUE TITLE
CS局の並びがおかしい

### ISSUE THREAD

**Issue by pikesaury** [xtne6f/EDCB#68]
いつのバージョンからかわかりませんが、CS局の番組表の並びがチャンネル順にならなくなりました。
例えばTvTestでは「55 ショップチャンネル」「161 QVC」と始まりますが、EDCBでは「296 TBSチャンネル1」「298 テレ朝チャンネル1」と始まります。こちらご確認いただけますでしょうか。

**Comment by xtne6f** [comment]
CSの並びについては、以前から、というか原作からいわゆるチャンネル順（番組表の番組名直下にある数字）には並びません。このフォークではいまのところサービスの並び順はこのようなルールになっています。

<EpgDataCap_Bonのサービス選択欄>
![edcb](https://github.com/user-attachments/assets/7b978b4f-0796-4f78-ba5d-3a3322fcbdfb)
**並び順** Settingフォルダにある.ChSet4.txtの順。

<EpgTimerのリストボックスなど>
![epgtimer](https://github.com/user-attachments/assets/c4048b34-9b33-46de-9b2d-0a2261a2da51)
**並び順**  「地デジ、BS、CS、その他」のグループに分けて、BSはサービスID順、ほかは放送ID(ONID,TSID,SID)の順。ただし「リストボックスなどのサービス一覧をIDでソートする」の設定をオフにしたときはSettingフォルダにあるChSet5.txtの順。

<EpgTimerのデフォルトの番組表やLegacy WebUI>
**並び順**  地デジはリモコンキー順、BSはサービスID順、ほかは放送IDの順。

なので、EpgTimerのデフォルトの番組表ではCSは放送ID(ONID,TSID,SID)の順に並ぶので、一見するとデタラメな感じに並ぶはずです。この挙動にとくに理由はなくて、ロジックが単純で原作からそのまま継承しているだけなのでこうなっています。

たぶんなのですが、ほかのフォークのEpgTimer、例えば[tkntrec版](https://github.com/tkntrec/EDCB)ではこの並び順のルールが改善されているので、それらと混同しているのではないかと思います。WebUIについてもほかのWebUIの並び順はWebUIごとのルールで並ぶので、このフォークとしてはとくに仕様変更はないと思います。

**Comment by pikesaury** [comment]
ご回答ありがとうございました。理解できました。Closeさせて頂きます。
